/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { motion } from 'motion/react';
import { Sparkles, CalendarPlus, CheckCircle2, RefreshCw, Layers } from 'lucide-react';
import { ExecutionPlan } from '../types';
import { approveExecutionPlan } from '../api';
import { auth, getUserPlans, getUserEvents, saveUserPlan, saveUserEvent } from '../firebase';

interface ExecutionPlanViewProps {
  plan: ExecutionPlan | null;
  onPlanApproved: () => void;
  onRegenerate: () => void;
  isGenerating: boolean;
}

export default function ExecutionPlanView({ plan, onPlanApproved, onRegenerate, isGenerating }: ExecutionPlanViewProps) {
  const [isApproving, setIsApproving] = useState(false);

  const handleApprove = async () => {
    if (!plan) return;
    setIsApproving(true);
    try {
      const currentUser = auth.currentUser;
      if (currentUser) {
        const plans = await getUserPlans(currentUser.uid);
        const events = await getUserEvents(currentUser.uid);
        
        const response = await approveExecutionPlan(plan.id, plans as ExecutionPlan[], events);
        
        // Save the approved plan
        await saveUserPlan(currentUser.uid, plan.id, response.plan);
        
        // Save newly injected calendar events
        if (response.newEvents) {
          for (const ev of response.newEvents) {
            await saveUserEvent(currentUser.uid, ev.id, ev);
          }
        }
      } else {
        await approveExecutionPlan(plan.id);
      }
      onPlanApproved();
    } catch (err) {
      console.error(err);
    } finally {
      setIsApproving(false);
    }
  };

  return (
    <div className="bg-[#111114] border border-[#262626] rounded-3xl p-6 shadow-xl flex flex-col h-full" id="execution-plan-panel">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-[#262626] pb-3 mb-4">
        <div className="flex items-center gap-2">
          <Layers className="w-5 h-5 text-red-500" />
          <div>
            <h3 className="text-xs font-bold uppercase tracking-widest text-zinc-300">AI Session Strategy</h3>
            <p className="text-[10px] text-zinc-400">Tactical focus roadmap generated by Gemini</p>
          </div>
        </div>
        {plan && !plan.approved && (
          <button
            onClick={onRegenerate}
            disabled={isGenerating}
            className="p-1.5 hover:bg-zinc-800 rounded-lg text-zinc-400 hover:text-white transition cursor-pointer"
            title="Regenerate roadmap"
          >
            <RefreshCw className={`w-4 h-4 ${isGenerating ? 'animate-spin' : ''}`} />
          </button>
        )}
      </div>

      {/* Body */}
      <div className="flex-1 flex flex-col justify-between min-h-[200px]">
        {isGenerating ? (
          <div className="flex-1 flex flex-col items-center justify-center text-center p-6 space-y-3">
            <div className="w-10 h-10 rounded-xl bg-zinc-900 border border-[#262626] flex items-center justify-center text-red-400">
              <Sparkles className="w-5 h-5 animate-spin text-red-500" />
            </div>
            <div className="space-y-1">
              <p className="text-xs font-semibold text-white uppercase tracking-wider">Orchestrating Calendar Slots...</p>
              <p className="text-[10px] text-zinc-400">Gemini is checking calendar conflicts and calculating focus energy intervals</p>
            </div>
          </div>
        ) : plan ? (
          <div className="space-y-4">
            <div className="bg-zinc-900 border border-[#262626] rounded-xl p-3.5 flex flex-col gap-1">
              <span className="text-[9px] font-mono text-zinc-500 uppercase tracking-widest font-semibold">Target Goal</span>
              <span className="text-xs font-bold text-white">{plan.taskTitle}</span>
            </div>

            {/* Plan List */}
            <div className="space-y-2 max-h-[180px] overflow-y-auto pr-1 scrollbar-none">
              {plan.items.map((item, idx) => (
                <div
                  key={item.id}
                  className="flex items-center justify-between p-3 bg-zinc-900 border border-[#262626] rounded-2xl text-xs"
                >
                  <div className="flex items-center gap-3">
                    <span className="w-6 h-6 rounded-md bg-red-950/40 border border-red-900/40 flex items-center justify-center text-[10px] font-mono font-bold text-red-400">
                      #{idx + 1}
                    </span>
                    <div className="space-y-0.5">
                      <p className="font-semibold text-white">{item.phase}</p>
                      <p className="text-[10px] text-zinc-400">{item.day} · {item.timeSlot}</p>
                    </div>
                  </div>
                  <div className="text-right shrink-0">
                    <span className="text-[10px] font-mono text-zinc-300 bg-[#111114] px-2.5 py-1 rounded-md border border-[#262626]">
                      {item.duration}h session
                    </span>
                  </div>
                </div>
              ))}
            </div>

            {/* Approval Footer */}
            {!plan.approved ? (
              <div className="pt-3 border-t border-[#262626]/60 flex gap-2">
                <button
                  onClick={handleApprove}
                  disabled={isApproving}
                  className="w-full py-2.5 bg-red-600 hover:bg-red-500 disabled:bg-zinc-800 text-white rounded-xl text-xs font-bold uppercase tracking-wider flex items-center justify-center gap-1.5 shadow-[0_0_15px_rgba(220,38,38,0.25)] cursor-pointer transition duration-150"
                >
                  {isApproving ? (
                    <RefreshCw className="w-4 h-4 animate-spin" />
                  ) : (
                    <CalendarPlus className="w-4 h-4" />
                  )}
                  Approve & Inject Focus Slots
                </button>
              </div>
            ) : (
              <div className="p-3 bg-emerald-950/20 border border-emerald-900/40 rounded-xl flex items-center gap-2.5 text-emerald-400 text-xs">
                <CheckCircle2 className="w-5 h-5 shrink-0" />
                <div className="space-y-0.5">
                  <p className="font-bold uppercase tracking-wide">Execution Plan Active</p>
                  <p className="text-[10px] text-emerald-500">Sessions are fully scheduled in Google Calendar.</p>
                </div>
              </div>
            )}
          </div>
        ) : (
          /* Empty State */
          <div className="flex-1 flex flex-col items-center justify-center text-center p-6 text-zinc-500 space-y-2">
            <Layers className="w-8 h-8 text-zinc-600" />
            <div className="max-w-xs space-y-1">
              <p className="text-xs font-semibold text-white uppercase tracking-wider">No active roadmap</p>
              <p className="text-[10px] text-zinc-500">
                Generate an execution plan for a goal. The Chief of Staff will outline precise study/focus windows and resolve calendar conflicts automatically.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
