import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Bot, ShieldAlert, TrendingUp, CheckSquare, 
  Sparkles, Calendar, Layers, HelpCircle, 
  X, ChevronRight, ChevronLeft, Settings, Brain 
} from 'lucide-react';

interface HelpTourProps {
  isOpen: boolean;
  onComplete: () => void;
}

interface TourStep {
  title: string;
  description: string;
  selector: string | null;
  placement: 'top' | 'bottom' | 'left' | 'right' | 'center';
  icon: React.ReactNode;
}

export default function HelpTour({ isOpen, onComplete }: HelpTourProps) {
  const [currentStep, setCurrentStep] = useState(0);
  const [rect, setRect] = useState<{ top: number; left: number; width: number; height: number } | null>(null);
  const [windowWidth, setWindowWidth] = useState(typeof window !== 'undefined' ? window.innerWidth : 1024);

  const steps: TourStep[] = [
    {
      title: "Welcome, Commander",
      description: "Deadline Guardian AI is active. This cognitive shield automatically tracks high-stakes project goals, analyzes deadline risk, and maps focus blocks directly onto your calendar. Let's take a quick tactical tour.",
      selector: null,
      placement: 'center',
      icon: <Bot className="w-10 h-10 text-red-500" />
    },
    {
      title: "Monitored Goals",
      description: "This is your project cockpit. Create high-stakes deadlines here. Click STRATEGIZE on any task to trigger the AI agent to map out a custom micro-session plan for you, or click COMPLETE when done.",
      selector: "#help-goals-section",
      placement: 'right',
      icon: <CheckSquare className="w-10 h-10 text-red-500" />
    },
    {
      title: "Emergency Rescue Protocol",
      description: "Should a task risk level exceed 80% or you miss a calendar focus session, Rescue Mode activates automatically. Visual rings alert you, non-critical pacing is deferred, and emergency guides optimize your remaining time.",
      selector: "#help-rescue-card",
      placement: 'bottom',
      icon: <ShieldAlert className="w-10 h-10 text-red-500 animate-pulse" />
    },
    {
      title: "Cognitive Decision Hub",
      description: "This is the cognitive center showing your dynamic Productivity Index and total Focus Hours. It keeps your productivity capacity calibrated in real-time as you complete work.",
      selector: "#help-productivity-metrics",
      placement: 'bottom',
      icon: <TrendingUp className="w-10 h-10 text-red-500" />
    },
    {
      title: "AI Brain Dump Scheduler",
      description: "Have scattered thoughts or a messy list of items? Click Brain Dump, paste your raw thoughts, and the AI will extract goals and schedule them dynamically.",
      selector: "#brain-dump-trigger",
      placement: 'bottom',
      icon: <Brain className="w-10 h-10 text-red-500 animate-pulse" />
    },
    {
      title: "Priority Recommendation Engine",
      description: "Suffering from decision paralysis? Ask the AI Chief of Staff to analyze your timelines and calendar conflicts to select your single most critical next action item.",
      selector: "#cognitive-recommendation-trigger",
      placement: 'bottom',
      icon: <Sparkles className="w-10 h-10 text-red-500 animate-pulse" />
    },
    {
      title: "Google Calendar Sync",
      description: "Integrate your calendar. The AI automatically registers meeting conflicts and schedules dedicated 🎯 Focus Sessions during open slots to protect your time.",
      selector: "#help-calendar-section",
      placement: 'right',
      icon: <Calendar className="w-10 h-10 text-red-500" />
    },
    {
      title: "AI Strategy Plan",
      description: "Examine execution schedules generated by the AI. Review time slots, phases of execution, and confirm plan approvals to commit focus times directly to your system.",
      selector: "#help-plan-section",
      placement: 'left',
      icon: <Layers className="w-10 h-10 text-red-500" />
    },
    {
      title: "Chief of Staff Terminal",
      description: "Converse with your AI Chief of Staff. You can speak naturally or type command overrides such as 'Schedule a dev session for my demo project' or ask 'Which tasks are at risk today?'.",
      selector: "#help-chat-section",
      placement: 'left',
      icon: <Bot className="w-10 h-10 text-red-500" />
    },
    {
      title: "System Configuration Settings",
      description: "Securely input your private Gemini API Key. Stored safely in your cloud profile via Firestore (never in localStorage), this allows private execution of all AI strategy features.",
      selector: "#system-settings-trigger",
      placement: 'bottom',
      icon: <Settings className="w-10 h-10 text-red-500 animate-pulse" />
    },
    {
      title: "Tactical Briefings",
      description: "You are fully trained to command. If you ever need to go through this system briefing again, simply click this Help icon in the top header menu.",
      selector: "#help-tour-trigger",
      placement: 'bottom',
      icon: <HelpCircle className="w-10 h-10 text-red-500" />
    }
  ];

  // Track window resizing
  useEffect(() => {
    const handleResize = () => setWindowWidth(window.innerWidth);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Update target bounding box on current step change
  useEffect(() => {
    if (!isOpen) return;
    const step = steps[currentStep];
    if (!step.selector) {
      setRect(null);
      return;
    }

    const updateRect = () => {
      const el = document.querySelector(step.selector!);
      if (el) {
        // Scroll the element to the center of the viewport.
        // We use 'center' to keep the focused element in view and avoid scrolling it under the sticky header.
        const blockAlign: ScrollIntoViewOptions['block'] = 'center';
        el.scrollIntoView({ behavior: 'smooth', block: blockAlign });
        
        // Wait briefly for scroll to settle, then capture rect relative to viewport
        setTimeout(() => {
          const r = el.getBoundingClientRect();
          setRect({
            top: r.top,
            left: r.left,
            width: r.width,
            height: r.height
          });
        }, 100);
      } else {
        setRect(null);
      }
    };

    updateRect();
    // Extra timeout triggers to guarantee accurate layout after scrolling settles
    const timer1 = setTimeout(updateRect, 300);
    const timer2 = setTimeout(updateRect, 600);

    window.addEventListener('resize', updateRect);
    window.addEventListener('scroll', updateRect);

    return () => {
      clearTimeout(timer1);
      clearTimeout(timer2);
      window.removeEventListener('resize', updateRect);
      window.removeEventListener('scroll', updateRect);
    };
  }, [currentStep, isOpen]);

  if (!isOpen) return null;

  const isMobile = windowWidth < 768;
  const activeStep = steps[currentStep];

  // Positioning logic for desktop viewports
  const getTooltipStyle = () => {
    if (isMobile || !rect) {
      return isMobile
        ? {
            position: 'fixed' as const,
            bottom: '24px',
            left: '16px',
            right: '16px',
            zIndex: 50,
          }
        : {
            position: 'fixed' as const,
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            zIndex: 50,
            width: '100%',
            maxWidth: '440px'
          };
    }

    const offset = 20;
    let placement = activeStep.placement;

    // Flip horizontal placement dynamically if target leaves insufficient viewport space
    if (placement === 'left' && rect.left < 380 + offset + 16) {
      placement = 'right';
    } else if (placement === 'right' && (windowWidth - (rect.left + rect.width)) < 380 + offset + 16) {
      placement = 'left';
    }

    // Flip vertical placement dynamically if target leaves insufficient viewport space above/below
    if (placement === 'top' && rect.top < 240) {
      placement = 'bottom';
    } else if (placement === 'bottom' && (window.innerHeight - (rect.top + rect.height)) < 240) {
      placement = 'top';
    }

    // Clamp horizontal position so tooltip card never overflows screen edges
    const tooltipWidth = 380;
    const padding = 16;
    const minLeft = (tooltipWidth / 2) + padding; // 206
    const maxLeft = windowWidth - (tooltipWidth / 2) - padding;
    let leftVal = rect.left + rect.width / 2;
    if (minLeft < maxLeft) {
      leftVal = Math.max(minLeft, Math.min(maxLeft, leftVal));
    }

    switch (placement) {
      case 'bottom':
        return {
          position: 'fixed' as const,
          top: `${rect.top + rect.height + offset}px`,
          left: `${leftVal}px`,
          transform: 'translateX(-50%)',
          zIndex: 50,
          width: '100%',
          maxWidth: '380px'
        };
      case 'top':
        return {
          position: 'fixed' as const,
          top: `${rect.top - offset}px`,
          left: `${leftVal}px`,
          transform: 'translate(-50%, -100%)',
          zIndex: 50,
          width: '100%',
          maxWidth: '380px'
        };
      case 'left':
        return {
          position: 'fixed' as const,
          top: `${rect.top + rect.height / 2}px`,
          left: `${rect.left - offset}px`,
          transform: 'translate(-100%, -50%)',
          zIndex: 50,
          width: '100%',
          maxWidth: '380px'
        };
      case 'right':
        return {
          position: 'fixed' as const,
          top: `${rect.top + rect.height / 2}px`,
          left: `${rect.left + rect.width + offset}px`,
          transform: 'translateY(-50%)',
          zIndex: 50,
          width: '100%',
          maxWidth: '380px'
        };
      default:
        return {
          position: 'fixed' as const,
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%)',
          zIndex: 50,
          width: '100%',
          maxWidth: '440px'
        };
    }
  };

  const handleNext = () => {
    if (currentStep < steps.length - 1) {
      setCurrentStep(prev => prev + 1);
    } else {
      onComplete();
    }
  };

  const handleBack = () => {
    if (currentStep > 0) {
      setCurrentStep(prev => prev - 1);
    }
  };

  return (
    <div className="fixed inset-0 z-50 overflow-hidden pointer-events-none" id="help-tour-container">
      {/* Darkened overlay using SVG Mask Cutout */}
      <AnimatePresence>
        <svg className="fixed inset-0 w-full h-full pointer-events-auto z-30 transition-all duration-300">
          <defs>
            <mask id="tour-cutout-mask">
              {/* Entire screen is white (masked/opaque) */}
              <rect width="100%" height="100%" fill="white" />
              {/* Target cutout box is black (transparent hole) */}
              {rect && !isMobile && (
                <motion.rect
                  initial={false}
                  animate={{
                    x: rect.left - 8,
                    y: rect.top - 8,
                    width: rect.width + 16,
                    height: rect.height + 16,
                  }}
                  transition={{ type: "spring", stiffness: 120, damping: 20 }}
                  rx={16}
                  ry={16}
                  fill="black"
                />
              )}
            </mask>
          </defs>
          <rect
            width="100%"
            height="100%"
            fill="rgba(5, 5, 5, 0.75)"
            mask="url(#tour-cutout-mask)"
            className="backdrop-blur-[2px]"
          />
        </svg>
      </AnimatePresence>

      {/* Pulsing visual outline highlight box on desktop */}
      {rect && !isMobile && (
        <motion.div
          initial={false}
          animate={{
            top: rect.top - 8,
            left: rect.left - 8,
            width: rect.width + 16,
            height: rect.height + 16,
          }}
          transition={{ type: "spring", stiffness: 120, damping: 20 }}
          className="fixed pointer-events-none border-2 border-red-500 rounded-2xl z-40 shadow-[0_0_30px_rgba(220,38,38,0.25)]"
          style={{ boxSizing: 'border-box' }}
        >
          {/* Subtle glowing ring decoration */}
          <span className="absolute inset-0 rounded-2xl border border-red-400/40 animate-ping opacity-45" style={{ animationDuration: '3s' }} />
        </motion.div>
      )}

      {/* Onboarding Dialog Card */}
      <AnimatePresence mode="wait">
        <motion.div
          key={currentStep}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          style={getTooltipStyle()}
          className="fixed pointer-events-none z-50"
        >
          <motion.div
            initial={{ scale: 0.95, y: isMobile ? 20 : 15 }}
            animate={{ scale: 1, y: 0 }}
            exit={{ scale: 0.95, y: isMobile ? 20 : 15 }}
            transition={{ duration: 0.2 }}
            className="w-full bg-[#0b0b0d]/95 backdrop-blur-xl border border-zinc-800/90 rounded-3xl p-6 md:p-7 shadow-2xl shadow-black/80 flex flex-col gap-5 pointer-events-auto border-t-red-600/60 border-t-2 font-sans"
          >
            {/* Card Header */}
            <div className="flex items-start gap-4">
              <div className="p-3 bg-[#111114] border border-[#262626] rounded-2xl shadow-inner shrink-0 text-red-500">
                {activeStep.icon}
              </div>
              <div className="space-y-1.5 flex-1 min-w-0">
                <h4 className="text-base font-bold text-white tracking-tight leading-snug">
                  {activeStep.title}
                </h4>
                <div className="flex gap-1.5">
                  {steps.map((_, idx) => (
                    <span
                      key={idx}
                      className={`h-1.5 rounded-full transition-all duration-300 ${
                        idx === currentStep ? 'w-5 bg-red-600' : 'w-1.5 bg-zinc-800'
                      }`}
                    />
                  ))}
                </div>
              </div>
              <button
                onClick={onComplete}
                className="text-zinc-500 hover:text-white transition duration-150 p-1 rounded-lg hover:bg-zinc-800/40 cursor-pointer self-start"
                title="Skip briefing"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Description */}
            <p className="text-xs md:text-[13px] text-zinc-400 font-normal leading-relaxed">
              {activeStep.description}
            </p>

            {/* Actions Footer */}
            <div className="flex items-center justify-between border-t border-zinc-900 pt-4 mt-1">
              <button
                onClick={onComplete}
                className="text-[11px] text-zinc-500 hover:text-zinc-300 font-bold uppercase tracking-wider transition duration-150 cursor-pointer"
              >
                Skip Intro
              </button>

              <div className="flex items-center gap-3">
                {currentStep > 0 && (
                  <button
                    onClick={handleBack}
                    className="px-4 py-2 border border-zinc-800 hover:border-zinc-700 bg-zinc-900/40 text-zinc-300 hover:text-white rounded-xl text-[11px] font-bold tracking-wider uppercase transition duration-150 flex items-center gap-1 cursor-pointer"
                  >
                    <ChevronLeft className="w-3.5 h-3.5" />
                    Back
                  </button>
                )}

                <button
                  onClick={handleNext}
                  className="px-5 py-2.5 bg-red-600 hover:bg-red-500 text-white rounded-xl text-[11px] font-bold tracking-wider uppercase transition duration-150 flex items-center gap-1 shadow-[0_0_15px_rgba(220,38,38,0.25)] hover:shadow-[0_0_20px_rgba(220,38,38,0.4)] cursor-pointer"
                >
                  <span>{currentStep === steps.length - 1 ? 'Finish' : 'Next'}</span>
                  <ChevronRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          </motion.div>
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
